% Generated by MATLAB(R) 9.10 (R2021a) and Communications Toolbox 7.5 (R2021a).
% Generated on: 04-Dec-2021 16:42:44
%% 只有matlab2021能跑
%% Generate Bluetooth Low Energy Waveform
% Bluetooth Low Energy configuration:
% input bit source:
in = randi([0, 1], 1000, 1);
% waveform generation:
waveform = bleWaveformGenerator(in, 'Mode', 'LE2M', ...
    'SamplesPerSymbol', 8, ...
    'ChannelIndex', 37, ...
    'AccessAddress', [0 1 1 0 1 0 1 1 0 1 1 1 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 1 0 0 0 1]');

waveform_blue=[];
for i=1:20
    waveform_blue=[waveform_blue;waveform];
end

waveform_blue = resample(waveform_blue,12,25);
Fs = 7.68e6; 								 % sample rate of waveform
waveform_blue=waveform_blue(1:7.68e4);
% waveform_blue=resampl(waveform_blue,1,2);
%% Visualize Bluetooth Low Energy Waveform
% Spectrum Analyzer
% spectrum = dsp.SpectrumAnalyzer('SampleRate', Fs);
% spectrum(waveform);
% release(spectrum);

% % Constellation Diagram
% constel = comm.ConstellationDiagram('ColorFading', true, ...
%     'ShowTrajectory', 1, ...
%     'ShowReferenceConstellation', false);
% constel(waveform);
% release(constel);
% 
% % Eye Diagram
% eyediagram(waveform, 2* 8);


